### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DanielBoettner** [YanWenKun/ComfyUI-Docker#100]
Hello and thank you for your work on this.

I'd like to make a suggestion.

While I use the cu124-megapack I still would like to get access to the output files.
I can navigate to the files on my host machine but would have to manually `chown` them.
So, a solution to change the permissions of the output files would be useful.

# My current soultion is the following

## .env file

```
USER_ID=1000
GROUP_ID=1000
ENABLE_CRON=true
```

## custom docker-compose.yml

**This is my custom docker compose so the container can be accessed via my reverse proxy.**

```
services:
  comfyui:
    init: true
    container_name: comfyui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_CRON: ${ENABLE_CRON}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - "./storage:/root"
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      - 'traefik.http.routers.comfyui-http.rule=Host(`comfyui.jarvis.local`)'  # Replace with your desired domain
      - 'traefik.http.routers.comfyui-http.entrypoints=http'
      - 'traefik.http.routers.comfyui-http.tls=false'
      - 'traefik.http.routers.comfyui-https.rule=Host(`comfyui.jarvis.local`)'
      - 'traefik.http.routers.comfyui-https.entrypoints=https'
      - 'traefik.http.routers.comfyui-https.tls=true'
      - 'traefik.http.services.comfyui-https.loadbalancer.server.port=8188'
    networks:
      - traefik-network
    restart: unless-stopped

networks:
  traefik-network:
    external: true
```

The important part is just the 

```
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_CRON: ${ENABLE_CRON}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - CLI_ARGS=
```

## custom entrypoint

```
#!/bin/bash

# Start cron in the background
echo "[INFO] Starting cron..."
/usr/sbin/cron &

# Execute the original entrypoint script
echo "[INFO] Starting original entrypoint..."
exec bash /runner-scripts/entrypoint.sh

```

## fix-permissions.sh 

```
#!/bin/bash

# Path to the mounted directory
TARGET_DIR="/root/ComfyUI/output"

# Log the environment variables
echo "$(date '+%Y-%m-%d %H:%M:%S') [DEBUG] USER_ID=${USER_ID}, GROUP_ID=${GROUP_ID}" >> /var/log/cron.log

# Ensure the directory exists
if [ -d "$TARGET_DIR" ]; then
  echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] Adjusting permissions for $TARGET_DIR..."
  chown -R ${USER_ID}:${GROUP_ID} "$TARGET_DIR"  # Use environment variables
  chmod -R 775 "$TARGET_DIR"
else
  echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] Target directory $TARGET_DIR does not exist. Skipping permission adjustment."
fi

```

# notes

I didn't use SUSE Linux for quite some time. So forgive me if I made this more complicated than it needs to be.

During my testing this seemed to be the easiest way. Without having to change more of the containers behavior (e.g. systemd).

This could also be simplified by using an `/entrypoints` directory to place entrypoint scripts in the container. 

```
/entrypoints/
├── 01-setup-environment.sh
├── 02-start-services.sh
├── 03-custom-logic.sh
└── 99-entrypoint.sh
```

And let containers entrypoint iterate over these.
