### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by konsumer** [YanWenKun/ComfyUI-Docker#60]
On a host that has nvidia card, with this docker-compose.yml:

```yml
services:
  comfyui:
    image: yanwk/comfyui-boot:comfy3d-pt23
    restart: unless-stopped
    runtime: nvidia
    environment:
      CUDA_VISIBLE_DEVICES: all
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - 8188:8188
    volumes:
      - ${CONFIG}/comfyui:/root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu", "compute", "utility"]
```

It seems liek everything is setup right:

```
❯ docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi

Sat Sep 14 01:04:28 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     Off |   00000000:01:00.0  On |                  N/A |
|  0%   44C    P8              9W /  160W |     520MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

Do I need to do something else?

**Comment by konsumer** [comment]
Hmm, I restarted, and tried removing `runtime` and it seemed to help:

```yml
  comfyui:
    image: yanwk/comfyui-boot:comfy3d-pt23
    restart: unless-stopped
    ports:
      - 8188:8188
    volumes:
      - ${CONFIG}/comfyui:/root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
