### ISSUE TITLE
Unable to run container (exit code 139)

### ISSUE THREAD

**Issue by vleeuwenmenno** [YanWenKun/ComfyUI-Docker#68]
The container just fails to start with the most basic settings:
```
❯ docker compose up
[+] Running 1/0
 ✔ Container comfyui-no-auth-comfyui-1  Re...                                       0.0s 
Attaching to comfyui-1
comfyui-1 exited with code 139

```

docker-compose.yml:
```
services:
  comfyui:
    ports:
      - 8188:8188
    volumes:
      - './storage:/home/runner'
      - /mnt/ai:/mnt/ai
    environment:
      - CLI_ARGS=
    image: yanwk/comfyui-boot:cu124-megapak
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities:
                - gpu
```
